# -*- coding: utf-8 -*-
"""art.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JY5QM_uC9-HtOzSqv_jup57J-mszDRHI
"""

# %reload_ext autoreload
# %autoreload 2
# %matplotlib inline

from pathlib import Path
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

from fastai.vision import *
from fastai.metrics import error_rate
from google.colab import drive

bs = 32


drive.mount('/content/gdrive')
DIR = Path('gdrive') / 'My Drive' / 'art' / 'costumes'

src = (ImageList.from_folder(DIR)
       .split_by_rand_pct(0.2)
       .label_from_folder()
       .transform(get_transforms(max_zoom=1.0, max_rotate=5), size=224))

db  = src.databunch(bs=16, num_workers=0).normalize(imagenet_stats)


learn = cnn_learner(db, models.vgg16_bn, metrics=error_rate)

learn.lr_find()

learn.recorder.plot()

learn.fit_one_cycle(5, 5e-3)

learn.unfreeze()

learn.lr_find()

learn.recorder.plot()

learn.fit_one_cycle(5, 7e-5)

learn.show_results()

interp = ClassificationInterpretation.from_learner(learn)

interp.plot_top_losses(9, figsize=(15,11))

interp.plot_confusion_matrix(figsize=(8, 8), dpi=100)


